server:
  port: 8088
 
Spring:
  messages:
    basename: messages
  jpa:
    show-sql: true
  security:
    user:
      name: oiui1072
      password: k1mjung12#
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        